import type { DignityProfile, GoalProgressLog } from '../types'
import type { IcfAssessment, IndividualLifePlan, RightsRealizationLog } from '@/types/database'

const now = new Date().toISOString()

export const DEMO_GOALS = [
  { id: 'g1', beneficiary_id: 'b001', domain: 'حركي', goal_title: 'المشي المستقل لمسافة 50 متر', goal_description: 'تحسين القدرة الحركية للمشي بدون مساعدة', measurement_type: 'distance', measurement_unit: 'متر', baseline_value: 10, target_value: 50, current_value: 35, quality_of_life_dimension: 'physical', start_date: '2026-01-01', target_date: '2026-06-01', assigned_to: 'أ. عادل العلي', assigned_department: 'العلاج الطبيعي', status: 'active' as const, progress_percentage: 70, achievement_evidence: null, barriers_notes: 'ألم في الركبة أحياناً', family_involvement: 'تشجيع مستمر', linked_national_goal: null, created_at: now, updated_at: now },
  { id: 'g2', beneficiary_id: 'b001', domain: 'تواصل', goal_title: 'نطق 20 كلمة جديدة', goal_description: 'توسيع المحصول اللغوي', measurement_type: 'count', measurement_unit: 'كلمة', baseline_value: 5, target_value: 20, current_value: 14, quality_of_life_dimension: 'social', start_date: '2026-01-15', target_date: '2026-07-15', assigned_to: 'أ. هدى المالكي', assigned_department: 'النطق والتخاطب', status: 'active' as const, progress_percentage: 60, achievement_evidence: null, barriers_notes: null, family_involvement: 'ممارسة في المنزل', linked_national_goal: null, created_at: now, updated_at: now },
  { id: 'g3', beneficiary_id: 'b002', domain: 'استقلالية', goal_title: 'ارتداء الملابس بشكل مستقل', goal_description: 'التدرب على ارتداء الملابس دون مساعدة', measurement_type: 'score', measurement_unit: 'درجة', baseline_value: 2, target_value: 10, current_value: 10, quality_of_life_dimension: 'independence', start_date: '2025-09-01', target_date: '2026-02-01', assigned_to: 'أ. نور العمري', assigned_department: 'العلاج الوظيفي', status: 'achieved' as const, progress_percentage: 100, achievement_evidence: 'تم التوثيق بالفيديو', barriers_notes: null, family_involvement: 'تدريب الأسرة', linked_national_goal: null, created_at: now, updated_at: now },
]

export const DEMO_LOGS: GoalProgressLog[] = [
  { id: 'pl1', goalId: 'g1', date: '2026-02-25', value: 35, note: 'تحسن ملحوظ — مشى 35 متر بدون مساعدة', recordedBy: 'أ. عادل العلي' },
  { id: 'pl2', goalId: 'g1', date: '2026-02-18', value: 28, note: 'زيادة تدريجية في المسافة', recordedBy: 'أ. عادل العلي' },
  { id: 'pl3', goalId: 'g2', date: '2026-02-20', value: 14, note: 'نطق 3 كلمات جديدة هذا الأسبوع', recordedBy: 'أ. هدى المالكي' },
]

export const DEMO_DIGNITY: DignityProfile = {
  id: 'd1',
  beneficiaryId: 'b001',
  preferredName: 'أبو سلطان',
  communicationStyle: 'بصري — يفضل الصور والإشارات',
  likes: ['الموسيقى الهادئة', 'الرسم', 'المشي في الحديقة'],
  dislikes: ['الأصوات العالية', 'الأماكن المزدحمة'],
  strengths: ['ذاكرة بصرية قوية', 'تعاون ممتاز'],
  motivators: ['المكافآت الغذائية', 'الثناء اللفظي'],
  calmingStrategies: ['الموسيقى الهادئة', 'الضغط العميق'],
  dreams: 'أحب أن أتعلم الرسم',
}

// ===== ICF Assessments Demo Data =====

export const DEMO_ICF_ASSESSMENTS: IcfAssessment[] = [
  {
    id: 'icf001',
    beneficiary_id: 'b001',
    assessment_date: now,
    assessor_id: 'أ. عادل العلي',
    component: 'd',
    icf_code: 'd4500',
    qualifier: null,
    capacity_qualifier: 2,
    performance_qualifier: 3,
    qualifier_type: null,
    qualifier_magnitude: null,
    notes: 'المشي لمسافات قصيرة — القدرة أفضل من الأداء بسبب عوائق بيئية',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'icf002',
    beneficiary_id: 'b001',
    assessment_date: now,
    assessor_id: 'أ. هدى المالكي',
    component: 'd',
    icf_code: 'd3100',
    qualifier: null,
    capacity_qualifier: 3,
    performance_qualifier: 3,
    qualifier_type: null,
    qualifier_magnitude: null,
    notes: 'التواصل واستقبال الرسائل اللفظية — صعوبة شديدة في كلا المُحدِّدين',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'icf003',
    beneficiary_id: 'b001',
    assessment_date: now,
    assessor_id: 'أ. عادل العلي',
    component: 'b',
    icf_code: 'b7100',
    qualifier: 2,
    capacity_qualifier: null,
    performance_qualifier: null,
    qualifier_type: null,
    qualifier_magnitude: null,
    notes: 'حركية مفصل واحد — صعوبة متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'icf004',
    beneficiary_id: 'b001',
    assessment_date: now,
    assessor_id: 'أ. نور العمري',
    component: 'e',
    icf_code: 'e1200',
    qualifier: null,
    capacity_qualifier: null,
    performance_qualifier: null,
    qualifier_type: 'barrier',
    qualifier_magnitude: 2,
    notes: 'المنتجات والتكنولوجيا للتنقل — عائق متوسط (عدم توفر أجهزة مناسبة)',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'icf005',
    beneficiary_id: 'b002',
    assessment_date: now,
    assessor_id: 'أ. نور العمري',
    component: 'd',
    icf_code: 'd5400',
    qualifier: null,
    capacity_qualifier: 1,
    performance_qualifier: 0,
    qualifier_type: null,
    qualifier_magnitude: null,
    notes: 'ارتداء الملابس — القدرة صعوبة خفيفة لكن الأداء ممتاز بفضل بيئة داعمة',
    created_at: now,
    updated_at: now,
  },
]

// ===== Individual Life Plans Demo Data =====

export const DEMO_LIFE_PLANS: IndividualLifePlan[] = [
  {
    id: 'lp001',
    beneficiary_id: 'b001',
    plan_period_start: '2026-01-01',
    plan_period_end: '2026-12-31',
    co_designed_with: ['أ. عادل العلي', 'أ. هدى المالكي', 'والد المستفيد'],
    beneficiary_participated: true,
    guardian_participated: true,
    emotional_wellbeing_goals: [{ goal: 'تحسين إدارة المشاعر والتعبير عنها', indicator: 'عدد نوبات القلق الأسبوعية', target: 'أقل من 2' }],
    interpersonal_relations_goals: [{ goal: 'بناء صداقة واحدة مع زميل', indicator: 'تفاعلات اجتماعية إيجابية', target: '3 أسبوعياً' }],
    material_wellbeing_goals: [],
    personal_development_goals: [{ goal: 'تعلّم الرسم الأساسي', indicator: 'لوحات منجزة', target: '12 سنوياً' }],
    physical_wellbeing_goals: [{ goal: 'المشي 50 متر بشكل مستقل', indicator: 'المسافة المقطوعة', target: '50 متر' }],
    self_determination_goals: [{ goal: 'اختيار النشاط اليومي بشكل مستقل', indicator: 'مرات الاختيار الذاتي', target: 'يومياً' }],
    social_inclusion_goals: [{ goal: 'المشاركة في نشاط مجتمعي شهري', indicator: 'أنشطة خارج المركز', target: '1 شهرياً' }],
    rights_goals: [{ goal: 'ضمان حق التعبير عن الرأي في كل اجتماع خطة', indicator: 'مشاركة فعّالة', target: '100%' }],
    status: 'active',
    review_date: '2026-06-01',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'lp002',
    beneficiary_id: 'b002',
    plan_period_start: '2026-01-01',
    plan_period_end: '2026-12-31',
    co_designed_with: ['أ. نور العمري', 'والدة المستفيد'],
    beneficiary_participated: true,
    guardian_participated: true,
    emotional_wellbeing_goals: [{ goal: 'زيادة الثقة بالنفس', indicator: 'مقياس الرضا الذاتي', target: '8/10' }],
    interpersonal_relations_goals: [],
    material_wellbeing_goals: [],
    personal_development_goals: [{ goal: 'إكمال برنامج التأهيل المهني', indicator: 'المهارات المكتسبة', target: '5 مهارات' }],
    physical_wellbeing_goals: [],
    self_determination_goals: [{ goal: 'إدارة الروتين الصباحي بشكل مستقل', indicator: 'الاستقلالية في الصباح', target: '100%' }],
    social_inclusion_goals: [],
    rights_goals: [],
    status: 'active',
    review_date: '2026-06-01',
    created_at: now,
    updated_at: now,
  },
]

// ===== Rights Realization Log Demo Data =====

export const DEMO_RIGHTS_LOG: RightsRealizationLog[] = [
  {
    id: 'rr001',
    beneficiary_id: 'b001',
    crpd_article: '12',
    right_domain: 'الاعتراف بالأهلية القانونية على قدم المساواة',
    status: 'partially_realized',
    barrier_description: 'يتم اتخاذ بعض القرارات نيابة عن المستفيد بدون إشراكه',
    action_required: 'تدريب الفريق على دعم اتخاذ القرار بدلاً من الاستبدال',
    logged_by: 'أ. نور العمري',
    logged_at: now,
    created_at: now,
  },
  {
    id: 'rr002',
    beneficiary_id: 'b001',
    crpd_article: '19',
    right_domain: 'العيش المستقل والاندماج المجتمعي',
    status: 'barrier_identified',
    barrier_description: 'لا يوجد برنامج انتقال مجتمعي — المستفيد يرغب في العيش شبه المستقل',
    action_required: 'تطوير مسار انتقال تدريجي مع دعم سكني مجتمعي',
    logged_by: 'أ. نور العمري',
    logged_at: now,
    created_at: now,
  },
  {
    id: 'rr003',
    beneficiary_id: 'b001',
    crpd_article: '24',
    right_domain: 'التعليم',
    status: 'realized',
    barrier_description: null,
    action_required: null,
    logged_by: 'أ. هدى المالكي',
    logged_at: now,
    created_at: now,
  },
  {
    id: 'rr004',
    beneficiary_id: 'b002',
    crpd_article: '27',
    right_domain: 'العمل والتوظيف',
    status: 'partially_realized',
    barrier_description: 'برنامج التأهيل المهني محدود — فرص العمل المحمي غير كافية',
    action_required: 'التواصل مع منصة قوى لفرص العمل المدعوم',
    logged_by: 'أ. نور العمري',
    logged_at: now,
    created_at: now,
  },
  {
    id: 'rr005',
    beneficiary_id: 'b002',
    crpd_article: '30',
    right_domain: 'المشاركة في الحياة الثقافية والترفيه',
    status: 'realized',
    barrier_description: null,
    action_required: null,
    logged_by: 'أ. نور العمري',
    logged_at: now,
    created_at: now,
  },
]
