import type { EmergencyPeepPlan, EmergencyEquipmentReadiness } from '@/types/database'

const now = new Date().toISOString()

export const DEMO_PEEP_PLANS: EmergencyPeepPlan[] = [
  {
    id: 'peep001',
    beneficiary_id: 'b001',
    evacuation_mobility_level: 'wheelchair',
    alarm_comprehension: 'partial',
    evacuation_method: 'evac_chair',
    primary_escort: 'محمد أحمد',
    secondary_escort: 'سعيد علي',
    primary_route: 'الممر الشرقي → المخرج B',
    alternative_route: 'الممر الغربي → المخرج A',
    special_equipment: ['كرسي إخلاء Evac+Chair 300H'],
    behavioral_considerations: 'قد يشعر بالقلق عند سماع الإنذار — استخدام التواصل الهادئ',
    communication_method: 'لفظي بسيط مع إشارات',
    medical_equipment_needed: ['جهاز أكسجين محمول'],
    last_drill_date: '2026-01-15',
    last_review_date: '2026-02-01',
    next_review_date: '2026-08-01',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'peep002',
    beneficiary_id: 'b002',
    evacuation_mobility_level: 'assisted',
    alarm_comprehension: 'none',
    evacuation_method: 'assisted_walk',
    primary_escort: 'فاطمة خالد',
    secondary_escort: 'نورة سعد',
    primary_route: 'الممر الشمالي → المخرج C',
    alternative_route: 'السلم الخارجي → المخرج D',
    special_equipment: [],
    behavioral_considerations: 'إعاقة ذهنية — لا يفهم التعليمات المعقدة، استخدام بطاقات صور',
    communication_method: 'بطاقات صور تعليمية',
    medical_equipment_needed: [],
    last_drill_date: '2026-01-15',
    last_review_date: '2026-02-01',
    next_review_date: '2026-08-01',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'peep004',
    beneficiary_id: 'b009',
    evacuation_mobility_level: 'wheelchair',
    alarm_comprehension: 'none',
    evacuation_method: 'evac_chair',
    primary_escort: 'نورة سعد',
    secondary_escort: 'خالد عمر',
    primary_route: 'الممر الشمالي → المخرج C',
    alternative_route: 'الممر الغربي → المخرج A',
    special_equipment: ['كرسي إخلاء Evac+Chair 300H'],
    behavioral_considerations: 'ضمور عضلي شوكي — يحتاج حمل كامل، لا يستطيع المشي. يتواصل عبر الآيباد',
    communication_method: 'جهاز لوحي AAC',
    medical_equipment_needed: ['جهاز تنفس محمول'],
    last_drill_date: '2026-01-15',
    last_review_date: '2026-02-15',
    next_review_date: '2026-08-15',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'peep003',
    beneficiary_id: 'b004',
    evacuation_mobility_level: 'stretcher',
    alarm_comprehension: 'none',
    evacuation_method: 'defend_in_place',
    primary_escort: 'عادل محمد',
    secondary_escort: 'يوسف عمر',
    primary_route: 'منطقة لجوء — الجناح الشرقي',
    alternative_route: null,
    special_equipment: ['حاجز دخان', 'جهاز اتصال EVC'],
    behavioral_considerations: 'طريح فراش — دفاع في المكان هو الخيار الأنسب',
    communication_method: 'إيماءات بسيطة',
    medical_equipment_needed: ['جهاز تنفس', 'مضخة تغذية'],
    last_drill_date: null,
    last_review_date: '2026-01-01',
    next_review_date: '2026-04-01',
    status: 'needs_review',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_EQUIPMENT: EmergencyEquipmentReadiness[] = [
  {
    id: 'eq001',
    equipment_name: 'كرسي إخلاء Evac+Chair 300H',
    equipment_type: 'evac_chair',
    location: 'الطابق الثاني - الممر الشرقي',
    section: 'ذكور',
    last_inspection_date: '2026-02-15',
    next_inspection_date: '2026-05-15',
    status: 'operational',
    inspector_name: 'فني: خالد',
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'eq002',
    equipment_name: 'طفاية حريق CO2 5kg',
    equipment_type: 'fire_extinguisher',
    location: 'الطابق الأول - المطبخ',
    section: null,
    last_inspection_date: '2026-01-10',
    next_inspection_date: '2026-04-10',
    status: 'operational',
    inspector_name: 'فني: خالد',
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'eq003',
    equipment_name: 'جهاز إزالة الرجفان AED',
    equipment_type: 'aed',
    location: 'الاستقبال الرئيسي',
    section: null,
    last_inspection_date: '2025-11-01',
    next_inspection_date: '2026-02-01',
    status: 'needs_maintenance',
    inspector_name: 'فني: خالد',
    notes: 'تجاوز موعد الفحص — يحتاج فحص فوري',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'eq004',
    equipment_name: 'نظام إنذار حريق - الجناح الغربي',
    equipment_type: 'alarm_system',
    location: 'الجناح الغربي',
    section: 'إناث',
    last_inspection_date: '2026-02-20',
    next_inspection_date: '2026-08-20',
    status: 'operational',
    inspector_name: 'فني: سالم',
    notes: null,
    created_at: now,
    updated_at: now,
  },
]
