import type { MedicalProfile } from '@/types/database'

const now = new Date().toISOString()

export const DEMO_MEDICAL_PROFILES: MedicalProfile[] = [
  {
    id: 'mp001',
    beneficiary_id: 'b001',
    primary_diagnosis: 'شلل دماغي - صرع',
    secondary_diagnoses: ['ضعف بصري'],
    chronic_diseases: ['صرع'],
    allergies: [],
    surgeries: [],
    family_history: 'لا يوجد تاريخ عائلي مرضي معروف',
    epilepsy: true,
    current_medications: [
      { name: 'كاربامازبين', dosage: '200 ملغ', frequency: 'مرتين يومياً' },
      { name: 'أملوديبين', dosage: '5 ملغ', frequency: 'مرة يومياً' },
    ],
    disability_type: 'حركية وعقلية',
    disability_degree: 'متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp002',
    beneficiary_id: 'b002',
    primary_diagnosis: 'متلازمة داون',
    secondary_diagnoses: [],
    chronic_diseases: [],
    allergies: ['البنسلين'],
    surgeries: ['إصلاح عيب خلقي في القلب - 2015'],
    family_history: null,
    epilepsy: false,
    current_medications: [
      { name: 'أوميبرازول', dosage: '20 ملغ', frequency: 'قبل الإفطار' },
    ],
    disability_type: 'ذهنية',
    disability_degree: 'بسيطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp003',
    beneficiary_id: 'b003',
    primary_diagnosis: 'توحد - إعاقة ذهنية',
    secondary_diagnoses: ['فرط حركة'],
    chronic_diseases: [],
    allergies: [],
    surgeries: [],
    family_history: null,
    epilepsy: false,
    current_medications: [
      { name: 'ريسبيريدون', dosage: '1 ملغ', frequency: 'مساءً' },
    ],
    disability_type: 'ذهنية',
    disability_degree: 'متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp004',
    beneficiary_id: 'b004',
    primary_diagnosis: 'شلل دماغي - سكري',
    secondary_diagnoses: ['ارتفاع ضغط الدم'],
    chronic_diseases: ['سكري نوع 2', 'ارتفاع ضغط'],
    allergies: [],
    surgeries: [],
    family_history: 'سكري وراثي',
    epilepsy: false,
    current_medications: [
      { name: 'أنسولين', dosage: '10 وحدات', frequency: 'قبل الوجبات' },
      { name: 'باراسيتامول', dosage: '500 ملغ', frequency: 'عند الحاجة' },
    ],
    disability_type: 'حركية',
    disability_degree: 'شديدة',
    created_at: now,
    updated_at: now,
  },
]
