import type { MedicalProfile } from '@/types/database'

const now = new Date().toISOString()

export const DEMO_MEDICAL_PROFILES: MedicalProfile[] = [
  {
    id: 'mp001',
    beneficiary_id: 'b001',
    primary_diagnosis: 'شلل دماغي - صرع',
    secondary_diagnoses: ['ضعف بصري'],
    chronic_diseases: ['صرع'],
    allergies: [],
    surgeries: [],
    family_history: 'لا يوجد تاريخ عائلي مرضي معروف',
    epilepsy: true,
    current_medications: [
      { name: 'كاربامازبين', dosage: '200 ملغ', frequency: 'مرتين يومياً' },
      { name: 'أملوديبين', dosage: '5 ملغ', frequency: 'مرة يومياً' },
    ],
    disability_type: 'حركية وعقلية',
    disability_degree: 'متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp002',
    beneficiary_id: 'b002',
    primary_diagnosis: 'متلازمة داون',
    secondary_diagnoses: [],
    chronic_diseases: [],
    allergies: ['البنسلين'],
    surgeries: ['إصلاح عيب خلقي في القلب - 2015'],
    family_history: null,
    epilepsy: false,
    current_medications: [
      { name: 'أوميبرازول', dosage: '20 ملغ', frequency: 'قبل الإفطار' },
    ],
    disability_type: 'ذهنية',
    disability_degree: 'بسيطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp003',
    beneficiary_id: 'b003',
    primary_diagnosis: 'توحد - إعاقة ذهنية',
    secondary_diagnoses: ['فرط حركة'],
    chronic_diseases: [],
    allergies: [],
    surgeries: [],
    family_history: null,
    epilepsy: false,
    current_medications: [
      { name: 'ريسبيريدون', dosage: '1 ملغ', frequency: 'مساءً' },
    ],
    disability_type: 'ذهنية',
    disability_degree: 'متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp004',
    beneficiary_id: 'b004',
    primary_diagnosis: 'شلل دماغي - سكري',
    secondary_diagnoses: ['ارتفاع ضغط الدم'],
    chronic_diseases: ['سكري نوع 2', 'ارتفاع ضغط'],
    allergies: [],
    surgeries: [],
    family_history: 'سكري وراثي',
    epilepsy: false,
    current_medications: [
      { name: 'أنسولين', dosage: '10 وحدات', frequency: 'قبل الوجبات' },
      { name: 'باراسيتامول', dosage: '500 ملغ', frequency: 'عند الحاجة' },
    ],
    disability_type: 'حركية',
    disability_degree: 'شديدة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp005',
    beneficiary_id: 'b009',
    primary_diagnosis: 'ضمور عضلي شوكي (SMA Type II)',
    secondary_diagnoses: ['جنف خفيف'],
    chronic_diseases: ['ضمور عضلي'],
    allergies: [],
    surgeries: ['تركيب قضيب نخاعي — 2022'],
    family_history: 'لا يوجد تاريخ عائلي مشابه',
    epilepsy: false,
    current_medications: [
      { name: 'نوسينيرسين', dosage: '12 ملغ', frequency: 'كل 4 أشهر — حقن قطني' },
    ],
    disability_type: 'حركية شديدة',
    disability_degree: 'شديدة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp006',
    beneficiary_id: 'b010',
    primary_diagnosis: 'إصابة دماغية رضية',
    secondary_diagnoses: ['ضعف بصري', 'صرع ثانوي'],
    chronic_diseases: ['صرع ثانوي'],
    allergies: ['الأسبرين'],
    surgeries: ['إزالة ورم دموي فوق الجافية — 2023'],
    family_history: null,
    epilepsy: true,
    current_medications: [
      { name: 'ليفيتيراسيتام', dosage: '500 ملغ', frequency: 'مرتين يومياً' },
      { name: 'جابابنتين', dosage: '300 ملغ', frequency: 'ثلاث مرات يومياً' },
    ],
    disability_type: 'حركية وبصرية',
    disability_degree: 'متوسطة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp007',
    beneficiary_id: 'b011',
    primary_diagnosis: 'إعاقة ذهنية شديدة + صرع مقاوم للعلاج',
    secondary_diagnoses: ['اضطراب سلوكي'],
    chronic_diseases: ['صرع'],
    allergies: [],
    surgeries: [],
    family_history: 'إعاقة ذهنية لدى أحد الأقارب',
    epilepsy: true,
    current_medications: [
      { name: 'فالبروات الصوديوم', dosage: '500 ملغ', frequency: 'ثلاث مرات يومياً' },
      { name: 'كلوبازام', dosage: '10 ملغ', frequency: 'مرتين يومياً' },
      { name: 'ليفيتيراسيتام', dosage: '750 ملغ', frequency: 'مرتين يومياً' },
    ],
    disability_type: 'ذهنية شديدة',
    disability_degree: 'شديدة',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mp008',
    beneficiary_id: 'b012',
    primary_diagnosis: 'متلازمة ريت',
    secondary_diagnoses: ['جنف', 'صعوبة تنفس'],
    chronic_diseases: ['صرع', 'جنف'],
    allergies: [],
    surgeries: [],
    family_history: null,
    epilepsy: true,
    current_medications: [
      { name: 'كاربامازبين', dosage: '100 ملغ', frequency: 'مرتين يومياً' },
      { name: 'باكلوفين', dosage: '5 ملغ', frequency: 'ثلاث مرات يومياً' },
    ],
    disability_type: 'ذهنية وحركية',
    disability_degree: 'شديدة',
    created_at: now,
    updated_at: now,
  },
]
