import type { UnifiedBeneficiaryProfile } from '../types'

const now = new Date().toISOString()

export const DEMO_BENEFICIARIES: UnifiedBeneficiaryProfile[] = [
  {
    id: 'b001',
    file_number: 'BEN-001',
    full_name: 'أحمد محمد السالم',
    national_id: '1234567890',
    gender: 'ذكر',
    date_of_birth: '2000-03-15',
    nationality: 'سعودي',
    section: 'ذكور',
    room_number: '12',
    bed_number: 'A',
    admission_date: '2024-01-10',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'محمد أحمد السالم',
    guardian_phone: '0551234567',
    guardian_relation: 'أب',
    medical_diagnosis: 'شلل دماغي - صرع',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [
      { id: 'epilepsy', label: 'صرع', color: 'red' },
    ],
    riskLevel: 'high',
    isOrphan: false,
    hasChronicCondition: true,
    requiresIsolation: false,
  },
  {
    id: 'b002',
    file_number: 'BEN-002',
    full_name: 'فاطمة عبدالله الزهراني',
    national_id: '2345678901',
    gender: 'أنثى',
    date_of_birth: '1998-07-22',
    nationality: 'سعودية',
    section: 'إناث',
    room_number: '8',
    bed_number: 'B',
    admission_date: '2023-09-05',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'عبدالله سعيد الزهراني',
    guardian_phone: '0559876543',
    guardian_relation: 'أب',
    medical_diagnosis: 'متلازمة داون',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [],
    riskLevel: 'low',
    isOrphan: false,
    hasChronicCondition: false,
    requiresIsolation: false,
  },
  {
    id: 'b003',
    file_number: 'BEN-003',
    full_name: 'خالد سعيد الغامدي',
    national_id: '1098765432',
    gender: 'ذكر',
    date_of_birth: '2005-11-03',
    nationality: 'سعودي',
    section: 'أطفال',
    room_number: '3',
    bed_number: 'A',
    admission_date: '2024-06-20',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: null,
    guardian_phone: null,
    guardian_relation: 'institution',
    medical_diagnosis: 'توحد - إعاقة ذهنية',
    notes: 'يتيم الأبوين',
    created_at: now,
    updated_at: now,
    smartTags: [
      { id: 'orphan', label: 'يتيم', color: 'gray' },
    ],
    riskLevel: 'medium',
    isOrphan: true,
    hasChronicCondition: false,
    requiresIsolation: false,
  },
  {
    id: 'b004',
    file_number: 'BEN-004',
    full_name: 'نورة حسن العتيبي',
    national_id: '2109876543',
    gender: 'أنثى',
    date_of_birth: '1995-04-18',
    nationality: 'سعودية',
    section: 'إناث',
    room_number: '15',
    bed_number: 'A',
    admission_date: '2023-02-14',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'حسن سالم العتيبي',
    guardian_phone: '0541112233',
    guardian_relation: 'أب',
    medical_diagnosis: 'شلل دماغي - سكري',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [
      { id: 'diabetic', label: 'سكري', color: 'orange' },
    ],
    riskLevel: 'high',
    isOrphan: false,
    hasChronicCondition: true,
    requiresIsolation: false,
  },
  {
    id: 'b005',
    file_number: 'BEN-005',
    full_name: 'سلطان ماجد القحطاني',
    national_id: '1567890123',
    gender: 'ذكر',
    date_of_birth: '2010-08-30',
    nationality: 'سعودي',
    section: 'أطفال',
    room_number: '5',
    bed_number: 'B',
    admission_date: '2024-11-01',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'ماجد سلطان القحطاني',
    guardian_phone: '0554445566',
    guardian_relation: 'أب',
    medical_diagnosis: 'إعاقة ذهنية بسيطة',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [],
    riskLevel: 'low',
    isOrphan: false,
    hasChronicCondition: false,
    requiresIsolation: false,
  },
  {
    id: 'b006',
    file_number: 'BEN-006',
    full_name: 'ريم عبدالرحمن الشهري',
    national_id: '2678901234',
    gender: 'أنثى',
    date_of_birth: '2002-12-25',
    nationality: 'سعودية',
    section: 'إناث',
    room_number: '10',
    bed_number: 'A',
    admission_date: '2024-03-18',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'عبدالرحمن محمد الشهري',
    guardian_phone: '0567778899',
    guardian_relation: 'أب',
    medical_diagnosis: 'متلازمة داون - صرع',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [
      { id: 'epilepsy', label: 'صرع', color: 'red' },
    ],
    riskLevel: 'high',
    isOrphan: false,
    hasChronicCondition: true,
    requiresIsolation: false,
  },
  {
    id: 'b007',
    file_number: 'BEN-007',
    full_name: 'عبدالعزيز فهد الدوسري',
    national_id: '1789012345',
    gender: 'ذكر',
    date_of_birth: '1990-06-12',
    nationality: 'سعودي',
    section: 'ذكور',
    room_number: '20',
    bed_number: 'B',
    admission_date: '2022-08-01',
    discharge_date: '2025-01-15',
    status: 'مخرج',
    evacuation_category: null,
    guardian_name: 'فهد سعيد الدوسري',
    guardian_phone: '0578889900',
    guardian_relation: 'أب',
    medical_diagnosis: 'إعاقة حركية',
    notes: 'تم تخريجه بعد تحسن ملحوظ',
    created_at: now,
    updated_at: now,
    smartTags: [],
    riskLevel: 'low',
    isOrphan: false,
    hasChronicCondition: false,
    requiresIsolation: false,
  },
  {
    id: 'b008',
    file_number: 'BEN-008',
    full_name: 'منال صالح البقمي',
    national_id: '2890123456',
    gender: 'أنثى',
    date_of_birth: '2008-01-20',
    nationality: 'سعودية',
    section: 'أطفال',
    room_number: '7',
    bed_number: 'A',
    admission_date: '2025-01-05',
    discharge_date: null,
    status: 'نشط',
    evacuation_category: null,
    guardian_name: 'صالح محمد البقمي',
    guardian_phone: '0589990011',
    guardian_relation: 'أب',
    medical_diagnosis: 'توحد',
    notes: null,
    created_at: now,
    updated_at: now,
    smartTags: [],
    riskLevel: 'low',
    isOrphan: false,
    hasChronicCondition: false,
    requiresIsolation: false,
  },
]
