import type { Risk, ComplianceRequirement, SafetyIncident } from '../types'

export const DEMO_RISKS: Risk[] = [
  {
    id: 'r1',
    riskCode: 'RSK-001',
    titleAr: 'نقص الكادر التمريضي',
    description: 'قد يؤدي نقص الكادر إلى تأخر تقديم الرعاية',
    category: 'operational',
    likelihood: 4,
    impact: 5,
    riskScore: 20,
    riskLevel: 'critical',
    riskOwner: 'مدير التمريض',
    department: 'إدارة التمريض',
    responseStrategy: 'mitigate',
    mitigationAction: 'تعيين 5 ممرضين إضافيين خلال Q1',
    status: 'identified',
    reviewFrequency: 'monthly',
  },
  {
    id: 'r2',
    riskCode: 'RSK-002',
    titleAr: 'تعطل نظام المعلومات',
    description: 'انقطاع النظام قد يؤثر على توثيق الرعاية',
    category: 'operational',
    likelihood: 2,
    impact: 5,
    riskScore: 10,
    riskLevel: 'high',
    riskOwner: 'تقنية المعلومات',
    department: 'إدارة تقنية المعلومات',
    responseStrategy: 'mitigate',
    mitigationAction: 'نسخ احتياطي يومي + خطة استمرارية',
    status: 'monitoring',
    reviewFrequency: 'quarterly',
  },
  {
    id: 'r3',
    riskCode: 'RSK-003',
    titleAr: 'تسرب بيانات حساسة',
    description: 'خطر تسرب بيانات المستفيدين الطبية',
    category: 'compliance',
    likelihood: 2,
    impact: 5,
    riskScore: 10,
    riskLevel: 'high',
    riskOwner: 'أمن المعلومات',
    department: 'إدارة أمن المعلومات',
    responseStrategy: 'avoid',
    mitigationAction: 'تشفير قاعدة البيانات + RLS + تدقيق دوري',
    status: 'monitoring',
    reviewFrequency: 'monthly',
  },
  {
    id: 'r4',
    riskCode: 'RSK-004',
    titleAr: 'حريق في المطبخ',
    description: 'خطر نشوب حريق بسبب معدات الطبخ',
    category: 'safety',
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    riskLevel: 'medium',
    riskOwner: 'إدارة السلامة',
    department: 'إدارة السلامة والأمن',
    responseStrategy: 'mitigate',
    mitigationAction: 'فحص دوري + طفايات حريق + تدريب الموظفين',
    status: 'monitoring',
    reviewFrequency: 'quarterly',
  },
  {
    id: 'r5',
    riskCode: 'RSK-005',
    titleAr: 'انتشار عدوى',
    description: 'خطر انتشار عدوى بين المستفيدين',
    category: 'safety',
    likelihood: 3,
    impact: 4,
    riskScore: 12,
    riskLevel: 'high',
    riskOwner: 'مكافحة العدوى',
    department: 'إدارة مكافحة العدوى',
    responseStrategy: 'mitigate',
    mitigationAction: 'تطبيق بروتوكولات IPC بصرامة',
    status: 'identified',
    reviewFrequency: 'monthly',
  },
  {
    id: 'r6',
    riskCode: 'RSK-006',
    titleAr: 'سقوط مستفيدين',
    description: 'خطر سقوط خاصة لكبار السن وذوي الإعاقة الحركية',
    category: 'safety',
    likelihood: 3,
    impact: 3,
    riskScore: 9,
    riskLevel: 'medium',
    riskOwner: 'التمريض',
    department: 'إدارة التمريض',
    responseStrategy: 'mitigate',
    mitigationAction: 'تقييم مورس + تدابير وقائية حسب مستوى الخطر',
    status: 'identified',
    reviewFrequency: 'quarterly',
  },
  {
    id: 'r7',
    riskCode: 'RSK-007',
    titleAr: 'تأخر صيانة المعدات',
    description: 'تأخر صيانة المعدات الطبية عن الجدول',
    category: 'operational',
    likelihood: 3,
    impact: 3,
    riskScore: 9,
    riskLevel: 'medium',
    riskOwner: 'إدارة التشغيل',
    department: 'إدارة التشغيل والصيانة',
    responseStrategy: 'transfer',
    mitigationAction: 'عقد صيانة شامل مع مورد خارجي',
    status: 'monitoring',
    reviewFrequency: 'quarterly',
  },
]

export const DEMO_COMPLIANCE: ComplianceRequirement[] = [
  {
    id: 'comp1',
    requirementCode: 'CR-001',
    titleAr: 'فهم المنظمة وسياقها',
    standardName: 'ISO 9001:2015',
    section: '4.1',
    complianceStatus: 'compliant',
    complianceScore: 100,
    responsibleDepartment: 'إدارة الجودة',
    evidenceNotes: 'تحليل SWOT محدث',
    gapDescription: '',
    remediationPlan: '',
    dueDate: '',
    lastAuditDate: '2026-01-15',
  },
  {
    id: 'comp2',
    requirementCode: 'CR-002',
    titleAr: 'القيادة والالتزام',
    standardName: 'ISO 9001:2015',
    section: '5.1',
    complianceStatus: 'compliant',
    complianceScore: 100,
    responsibleDepartment: 'الإدارة العليا',
    evidenceNotes: 'سياسة الجودة معتمدة من المدير',
    gapDescription: '',
    remediationPlan: '',
    dueDate: '',
    lastAuditDate: '2026-01-15',
  },
  {
    id: 'comp3',
    requirementCode: 'CR-003',
    titleAr: 'إجراءات معالجة المخاطر',
    standardName: 'ISO 9001:2015',
    section: '6.1',
    complianceStatus: 'partial',
    complianceScore: 60,
    responsibleDepartment: 'إدارة المخاطر',
    evidenceNotes: 'سجل المخاطر موجود',
    gapDescription: 'لم يتم تحديث المخاطر منذ 6 أشهر',
    remediationPlan: 'مراجعة ربع سنوية',
    dueDate: '2026-03-31',
    lastAuditDate: '2025-12-20',
  },
  {
    id: 'comp4',
    requirementCode: 'CR-004',
    titleAr: 'الكفاءة',
    standardName: 'ISO 9001:2015',
    section: '7.2',
    complianceStatus: 'compliant',
    complianceScore: 100,
    responsibleDepartment: 'إدارة الموارد البشرية',
    evidenceNotes: 'سجلات تدريب محدثة لجميع الموظفين',
    gapDescription: '',
    remediationPlan: '',
    dueDate: '',
    lastAuditDate: '2026-02-01',
  },
  {
    id: 'comp5',
    requirementCode: 'CR-005',
    titleAr: 'التحكم في تقديم الخدمة',
    standardName: 'ISO 9001:2015',
    section: '8.5.1',
    complianceStatus: 'partial',
    complianceScore: 60,
    responsibleDepartment: 'إدارة العمليات',
    evidenceNotes: 'إجراءات موثقة جزئياً',
    gapDescription: '3 إجراءات تحتاج تحديث',
    remediationPlan: 'تحديث الإجراءات المتبقية',
    dueDate: '2026-03-15',
    lastAuditDate: '2025-11-10',
  },
  {
    id: 'comp6',
    requirementCode: 'CR-006',
    titleAr: 'نسبة التوطين في التمريض',
    standardName: 'وزارة الموارد البشرية',
    section: 'معيار 3.2',
    complianceStatus: 'non_compliant',
    complianceScore: 0,
    responsibleDepartment: 'إدارة الموارد البشرية',
    evidenceNotes: 'نسبة حالية 15%',
    gapDescription: 'المطلوب 30% — فجوة 15%',
    remediationPlan: 'خطة توظيف سعوديين',
    dueDate: '2026-06-30',
    lastAuditDate: '2026-01-05',
  },
  {
    id: 'comp7',
    requirementCode: 'CR-007',
    titleAr: 'برنامج مكافحة عدوى فعال',
    standardName: 'مكافحة العدوى',
    section: 'CBAHI 1.5',
    complianceStatus: 'compliant',
    complianceScore: 100,
    responsibleDepartment: 'إدارة مكافحة العدوى',
    evidenceNotes: 'تقارير IPC شهرية + نتائج تدقيق',
    gapDescription: '',
    remediationPlan: '',
    dueDate: '',
    lastAuditDate: '2026-02-10',
  },
]

export const DEMO_SAFETY: SafetyIncident[] = [
  {
    id: 's1',
    incidentDate: '2026-02-22',
    incidentType: 'injury',
    severity: 'major',
    location: 'جناح ذكور A',
    description: 'سقوط مستفيد أثناء محاولة الذهاب للحمام ليلاً — تم نقله للطوارئ وتبين وجود كدمات بسيطة',
    reportedBy: 'نورة العتيبي',
    status: 'investigating',
    rootCause: 'عدم وجود مرافق ليلي + إضاءة ضعيفة في الممر',
    correctiveActions: 'تركيب إضاءة ليلية + تخصيص مرافق ليلي',
    injuries: 1,
  },
  {
    id: 's2',
    incidentDate: '2026-02-18',
    incidentType: 'other',
    severity: 'major',
    location: 'جناح إناث B',
    description: 'خطأ دوائي — جرعة مضاعفة من الباراسيتامول تم اكتشافها فوراً قبل حدوث أي ضرر',
    reportedBy: 'سارة القحطاني',
    status: 'closed',
    rootCause: 'عدم التحقق من سجل الأدوية قبل الصرف',
    correctiveActions: 'تطبيق نظام التحقق المزدوج للأدوية',
    injuries: 0,
  },
  {
    id: 's3',
    incidentDate: '2026-02-15',
    incidentType: 'other',
    severity: 'moderate',
    location: 'قاعة الأنشطة',
    description: 'سلوك عدواني من مستفيد تجاه مستفيد آخر أثناء جلسة النشاط الجماعي — تم التدخل فوراً',
    reportedBy: 'محمد الشهري',
    status: 'closed',
    rootCause: 'عدم كفاية الإشراف خلال الأنشطة الجماعية',
    correctiveActions: 'زيادة عدد المشرفين في الأنشطة الجماعية',
    injuries: 0,
  },
  {
    id: 's4',
    incidentDate: '2026-02-10',
    incidentType: 'injury',
    severity: 'minor',
    location: 'المطبخ',
    description: 'إصابة عمل — جرح بسيط لعامل المطبخ أثناء تقطيع الخضروات',
    reportedBy: 'أحمد الزهراني',
    status: 'closed',
    rootCause: 'عدم ارتداء قفازات السلامة أثناء التقطيع',
    correctiveActions: 'إلزام جميع العاملين بارتداء معدات السلامة',
    injuries: 1,
  },
]
